const DATA = {
  user: {
    name: 'สมหญิง วงศ์ดี',
    nickname: 'หญิง',
    avatar: 'ห',
    level: 'B1',
    streak: 14,
    xp: 1840,
    rank: 8,
    minutesToday: 52,
    vocabCount: 247,
    lessonsToday: 4,
    vocabReviewedToday: 18,
    joinDate: '2025-09-15',
    dailyGoalMinutes: 60,
    weeklyGoalLessons: 5,
    weeklyLessonsDone: 4,
  },

  levels: ['A1', 'A2', 'B1', 'B2', 'C1', 'C2'],
  currentLevel: 'B1',

  levelContent: {
    A1: {
      name: 'Beginner',
      nameTh: 'เริ่มต้น',
      color: '#10b981',
      description: 'เข้าใจและใช้สำนวนพื้นฐานในชีวิตประจำวัน แนะนำตัว ถามทิศทาง สั่งอาหาร',
      canDo: ['ทักทายและแนะนำตัว', 'ถาม-ตอบข้อมูลส่วนตัว', 'สั่งอาหารและเครื่องดื่ม', 'นับเลขและบอกเวลา', 'พูดถึงครอบครัวและงานอดิเรก'],
      grammar: [
        { topic: 'Verb to be (am / is / are)', rule: 'ใช้แสดงสถานะ อาชีพ สัญชาติ', examples: ['I am a student.', 'She is from Thailand.', 'They are happy.'] },
        { topic: 'Present Simple', rule: 'กิจวัตรประจำวัน ความจริงทั่วไป', examples: ['I work every day.', 'He likes coffee.', 'We live in Bangkok.'] },
        { topic: 'Articles (a / an / the)', rule: 'a/an สำหรับคำนามนับได้ the สำหรับคำเฉพาะ', examples: ['I have a cat.', 'She is an engineer.', 'The sun is hot.'] },
        { topic: 'Question words', rule: 'What, Where, When, Who, How', examples: ['What is your name?', 'Where do you live?', 'How old are you?'] },
      ],
      vocabulary: [
        { word: 'hello', meaning: 'สวัสดี', example: 'Hello! Nice to meet you.' },
        { word: 'family', meaning: 'ครอบครัว', example: 'I have a small family.' },
        { word: 'work', meaning: 'ทำงาน', example: 'I work in an office.' },
        { word: 'food', meaning: 'อาหาร', example: 'Thai food is delicious.' },
        { word: 'water', meaning: 'น้ำ', example: 'Can I have some water?' },
        { word: 'today', meaning: 'วันนี้', example: 'Today is Monday.' },
        { word: 'friend', meaning: 'เพื่อน', example: 'She is my best friend.' },
        { word: 'happy', meaning: 'มีความสุข', example: 'I am very happy today.' },
        { word: 'house', meaning: 'บ้าน', example: 'This is my house.' },
        { word: 'school', meaning: 'โรงเรียน', example: 'I go to school every morning.' },
        { word: 'book', meaning: 'หนังสือ', example: 'She is reading a book.' },
        { word: 'car', meaning: 'รถยนต์', example: 'He has a new car.' },
        { word: 'dog', meaning: 'สุนัข', example: 'The dog is very friendly.' },
        { word: 'cat', meaning: 'แมว', example: 'My cat likes to sleep.' },
        { word: 'name', meaning: 'ชื่อ', example: 'What is your name?' },
        { word: 'day', meaning: 'วัน', example: 'Have a nice day.' },
        { word: 'morning', meaning: 'ตอนเช้า', example: 'I drink coffee every morning.' },
        { word: 'night', meaning: 'กลางคืน', example: 'Good night, see you tomorrow.' },
        { word: 'big', meaning: 'ใหญ่', example: 'That is a big house.' },
        { word: 'small', meaning: 'เล็ก', example: 'I live in a small town.' },
        { word: 'good', meaning: 'ดี', example: 'This is a good idea.' },
        { word: 'bad', meaning: 'แย่', example: 'The weather is bad today.' },
        { word: 'eat', meaning: 'กิน', example: "Let's eat lunch together." },
        { word: 'drink', meaning: 'ดื่ม', example: 'I drink tea every day.' },
        { word: 'sleep', meaning: 'นอนหลับ', example: 'Babies sleep a lot.' },
        { word: 'walk', meaning: 'เดิน', example: 'We walk to school.' },
        { word: 'teacher', meaning: 'ครู', example: 'My teacher is very kind.' },
        { word: 'student', meaning: 'นักเรียน', example: 'I am a student.' },
        { word: 'mother', meaning: 'แม่', example: 'My mother cooks well.' },
        { word: 'father', meaning: 'พ่อ', example: 'My father works hard.' },
        { word: 'money', meaning: 'เงิน', example: 'I need more money.' },
        { word: 'shop', meaning: 'ร้านค้า', example: "Let's go to the shop." },
        { word: 'bus', meaning: 'รถบัส', example: 'I take the bus to work.' },
        { word: 'phone', meaning: 'โทรศัพท์', example: 'Can I use your phone?' },
        { word: 'table', meaning: 'โต๊ะ', example: 'Put the book on the table.' },
        { word: 'chair', meaning: 'เก้าอี้', example: 'Please sit on this chair.' },
        { word: 'door', meaning: 'ประตู', example: 'Please close the door.' },
        { word: 'window', meaning: 'หน้าต่าง', example: 'Open the window, please.' },
        { word: 'color', meaning: 'สี', example: 'What is your favorite color?' },
        { word: 'city', meaning: 'เมือง', example: 'Bangkok is a big city.' },
      ],
      phrases: [
        { en: 'Nice to meet you.', th: 'ยินดีที่ได้รู้จัก', context: 'ทักทายครั้งแรก' },
        { en: 'How much is this?', th: 'อันนี้เท่าไหร่', context: 'ซื้อของ' },
        { en: 'I don\'t understand.', th: 'ฉันไม่เข้าใจ', context: 'ขอความช่วยเหลือ' },
        { en: 'Where is the bathroom?', th: 'ห้องน้ำอยู่ที่ไหน', context: 'ถามทาง' },
      ],
      dialogues: [
        {
          title: 'แนะนำตัว',
          lines: [
            { speaker: 'A', en: 'Hi! My name is Tom. What\'s your name?', th: 'สวัสดี ผมชื่อทอม คุณชื่ออะไร' },
            { speaker: 'B', en: 'I\'m Lisa. Nice to meet you!', th: 'ฉันชื่อลิซ่า ยินดีที่ได้รู้จัก' },
            { speaker: 'A', en: 'Where are you from?', th: 'คุณมาจากไหน' },
            { speaker: 'B', en: 'I\'m from Japan. And you?', th: 'ฉันมาจากญี่ปุ่น แล้วคุณล่ะ' },
          ],
        },
      ],
      sentences: [
        { en: 'I am twenty-five years old.', th: 'ฉันอายุ 25 ปี', note: 'บอกอายุ' },
        { en: 'This is my book.', th: 'นี่คือหนังสือของฉัน', note: 'ทำความรู้จักสิ่งของ' },
        { en: 'I like reading and swimming.', th: 'ฉันชอบอ่านหนังสือและว่ายน้ำ', note: 'งานอดิเรก' },
      ],
    },

    A2: {
      name: 'Elementary',
      nameTh: 'พื้นฐาน',
      color: '#3b82f6',
      description: 'สื่อสารเรื่องง่ายๆ ในงานและชีวิตประจำวัน อดีต การเดินทาง สุขภาพ',
      canDo: ['เล่าประสบการณ์ในอดีต', 'วางแผนการเดินทาง', 'อธิบายอาการป่วย', 'เปรียบเทียบสิ่งของ', 'เขียนอีเมลสั้นๆ'],
      grammar: [
        { topic: 'Past Simple', rule: 'เหตุการณ์ในอดีตที่จบแล้ว', examples: ['I visited Paris last year.', 'She didn\'t come yesterday.', 'Did you see the movie?'] },
        { topic: 'Future (will / going to)', rule: 'แผนในอนาคต หรือการตัดสินใจทันที', examples: ['I will call you later.', 'We are going to travel next month.'] },
        { topic: 'Comparatives & Superlatives', rule: 'เปรียบเทียบ 2 สิ่ง หรือมากที่สุด', examples: ['This bag is cheaper than that one.', 'She is the tallest in the class.'] },
        { topic: 'Countable / Uncountable', rule: 'คำนามนับได้/ไม่ได้ some, any, much, many', examples: ['I need some water.', 'There aren\'t many chairs.'] },
      ],
      vocabulary: [
        { word: 'travel', meaning: 'เดินทาง', example: 'I love to travel abroad.' },
        { word: 'weather', meaning: 'อากาศ', example: 'The weather is nice today.' },
        { word: 'appointment', meaning: 'นัดหมาย', example: 'I have a doctor\'s appointment.' },
        { word: 'expensive', meaning: 'แพง', example: 'This phone is too expensive.' },
        { word: 'remember', meaning: 'จำได้', example: 'I remember that day clearly.' },
        { word: 'forget', meaning: 'ลืม', example: 'Don\'t forget your passport.' },
        { word: 'healthy', meaning: 'แข็งแรง', example: 'Eating vegetables keeps you healthy.' },
        { word: 'arrive', meaning: 'มาถึง', example: 'The train arrives at 9 AM.' },
        { word: 'journey', meaning: 'การเดินทาง', example: 'It was a long journey.' },
        { word: 'holiday', meaning: 'วันหยุด', example: 'We are on holiday this week.' },
        { word: 'hotel', meaning: 'โรงแรม', example: 'We stayed at a nice hotel.' },
        { word: 'airport', meaning: 'สนามบิน', example: 'The airport was very busy.' },
        { word: 'ticket', meaning: 'ตั๋ว', example: 'I bought two tickets.' },
        { word: 'luggage', meaning: 'กระเป๋าเดินทาง', example: 'Please check your luggage.' },
        { word: 'museum', meaning: 'พิพิธภัณฑ์', example: 'We visited the museum yesterday.' },
        { word: 'restaurant', meaning: 'ร้านอาหาร', example: 'Let\'s eat at that restaurant.' },
        { word: 'menu', meaning: 'เมนู', example: 'Can I see the menu, please?' },
        { word: 'bill', meaning: 'บิล / ใบเสร็จ', example: 'Can we have the bill, please?' },
        { word: 'hospital', meaning: 'โรงพยาบาล', example: 'He went to the hospital.' },
        { word: 'medicine', meaning: 'ยา', example: 'Take this medicine twice a day.' },
        { word: 'headache', meaning: 'ปวดหัว', example: 'I have a bad headache.' },
        { word: 'tired', meaning: 'เหนื่อย', example: 'I feel very tired today.' },
        { word: 'exercise', meaning: 'ออกกำลังกาย', example: 'I exercise every morning.' },
        { word: 'diet', meaning: 'อาหารการกิน', example: 'She is on a healthy diet.' },
        { word: 'borrow', meaning: 'ยืม', example: 'Can I borrow your pen?' },
        { word: 'lend', meaning: 'ให้ยืม', example: 'Could you lend me some money?' },
        { word: 'save', meaning: 'ประหยัด / เก็บออม', example: 'I try to save money each month.' },
        { word: 'spend', meaning: 'ใช้จ่าย', example: 'We spent a lot on the trip.' },
        { word: 'invite', meaning: 'เชิญ', example: 'I invited my friends to the party.' },
        { word: 'celebrate', meaning: 'เฉลิมฉลอง', example: 'We celebrated her birthday.' },
        { word: 'birthday', meaning: 'วันเกิด', example: 'Happy birthday to you!' },
        { word: 'wedding', meaning: 'งานแต่งงาน', example: 'We went to their wedding.' },
        { word: 'neighbor', meaning: 'เพื่อนบ้าน', example: 'My neighbor is very friendly.' },
        { word: 'apartment', meaning: 'อพาร์ตเมนต์', example: 'I live in a small apartment.' },
        { word: 'furniture', meaning: 'เฟอร์นิเจอร์', example: 'We bought new furniture.' },
        { word: 'kitchen', meaning: 'ครัว', example: 'She is cooking in the kitchen.' },
        { word: 'garden', meaning: 'สวน', example: 'He is working in the garden.' },
        { word: 'traffic', meaning: 'การจราจร', example: 'The traffic was terrible this morning.' },
        { word: 'direction', meaning: 'ทิศทาง', example: 'Could you give me directions?' },
        { word: 'map', meaning: 'แผนที่', example: 'Let\'s look at the map.' },
      ],
      phrases: [
        { en: 'Could you help me, please?', th: 'ช่วยฉันหน่อยได้ไหม', context: 'ขอความช่วยเหลือสุภาพ' },
        { en: 'I used to live in Chiang Mai.', th: 'ฉันเคยอยู่เชียงใหม่', context: 'เล่าอดีต' },
        { en: 'I\'m looking forward to it.', th: 'ฉันตั้งตารอ', context: 'แสดงความคาดหวัง' },
        { en: 'It depends on the weather.', th: 'ขึ้นอยู่กับอากาศ', context: 'ตอบแบบไม่แน่นอน' },
      ],
      dialogues: [
        {
          title: 'ที่ร้านอาหาร',
          lines: [
            { speaker: 'Waiter', en: 'Are you ready to order?', th: 'พร้อมสั่งอาหารหรือยัง' },
            { speaker: 'Customer', en: 'Yes, I\'d like the grilled chicken, please.', th: 'ครับ ขอไก่ย่างค่ะ' },
            { speaker: 'Waiter', en: 'Would you like anything to drink?', th: 'ต้องการเครื่องดื่มไหม' },
            { speaker: 'Customer', en: 'Just water, thank you.', th: 'น้ำเปล่าพอค่ะ ขอบคุณ' },
          ],
        },
      ],
      sentences: [
        { en: 'I went to the market yesterday.', th: 'ฉันไปตลาดเมื่อวาน', note: 'Past Simple' },
        { en: 'She is taller than her brother.', th: 'เธอสูงกว่าพี่ชาย', note: 'Comparative' },
        { en: 'We are going to visit grandma this weekend.', th: 'เราจะไปเยี่ยมคุณยายสุดสัปดาห์นี้', note: 'Going to' },
      ],
    },

    B1: {
      name: 'Intermediate',
      nameTh: 'กลาง',
      color: '#f59e0b',
      description: 'จัดการสถานการณ์ส่วนใหญ่เมื่อเดินทาง แสดงความคิดเห็น อธิบายประสบการณ์',
      canDo: ['แสดงความคิดเห็นและเหตุผล', 'เล่าเรื่องราวและประสบการณ์', 'เขียนจดหมายและอีเมล', 'เข้าใจข่าวง่ายๆ', 'พูดคุยเรื่องงานและการศึกษา'],
      grammar: [
        { topic: 'Present Perfect', rule: 'ประสบการณ์ในอดีต หรือเริ่มในอดีตต่อเนื่องถึงปัจจุบัน', examples: ['I have lived here for 5 years.', 'Have you ever been to Japan?', 'She has just finished.'] },
        { topic: 'First Conditional', rule: 'If + Present, will + V — เงื่อนไขที่เป็นไปได้', examples: ['If it rains, I will stay home.', 'If you study hard, you will pass.'] },
        { topic: 'Passive Voice (basic)', rule: 'เน้น action มากกว่า subject', examples: ['English is spoken worldwide.', 'The book was written in 1990.'] },
        { topic: 'Reported Speech', rule: 'เล่าสิ่งที่คนอื่นพูด', examples: ['She said she was tired.', 'He told me he would come.'] },
      ],
      vocabulary: [
        { word: 'accomplish', meaning: 'ทำสำเร็จ', example: 'She accomplished all her goals.' },
        { word: 'gratitude', meaning: 'ความกตัญญู', example: 'I expressed my gratitude to the team.' },
        { word: 'negotiate', meaning: 'เจรจา', example: 'They negotiated a better salary.' },
        { word: 'diligent', meaning: 'ขยัน', example: 'He is a diligent worker.' },
        { word: 'authentic', meaning: 'แท้จริง', example: 'This is authentic Thai cuisine.' },
        { word: 'opportunity', meaning: 'โอกาส', example: 'Learning English opens many opportunities.' },
        { word: 'environment', meaning: 'สิ่งแวดล้อม', example: 'We must protect the environment.' },
        { word: 'experience', meaning: 'ประสบการณ์', example: 'It was an unforgettable experience.' },
        { word: 'achieve', meaning: 'บรรลุผล', example: 'She achieved great success.' },
        { word: 'challenge', meaning: 'ความท้าทาย', example: 'This project is a big challenge.' },
        { word: 'confident', meaning: 'มั่นใจ', example: 'He felt confident about the exam.' },
        { word: 'improve', meaning: 'พัฒนาให้ดีขึ้น', example: 'I want to improve my English.' },
        { word: 'increase', meaning: 'เพิ่มขึ้น', example: 'Sales increased last month.' },
        { word: 'decrease', meaning: 'ลดลง', example: 'The price decreased recently.' },
        { word: 'decision', meaning: 'การตัดสินใจ', example: 'It was a difficult decision.' },
        { word: 'responsible', meaning: 'รับผิดชอบ', example: 'She is responsible for the project.' },
        { word: 'suggest', meaning: 'แนะนำ', example: 'I suggest we leave early.' },
        { word: 'recommend', meaning: 'แนะนำ', example: 'Can you recommend a good book?' },
        { word: 'purpose', meaning: 'จุดประสงค์', example: 'What is the purpose of this meeting?' },
        { word: 'advantage', meaning: 'ข้อดี', example: 'There are many advantages to this plan.' },
        { word: 'disadvantage', meaning: 'ข้อเสีย', example: 'Every choice has disadvantages.' },
        { word: 'develop', meaning: 'พัฒนา', example: 'The company developed a new product.' },
        { word: 'communicate', meaning: 'สื่อสาร', example: 'We need to communicate clearly.' },
        { word: 'relationship', meaning: 'ความสัมพันธ์', example: 'They have a close relationship.' },
        { word: 'community', meaning: 'ชุมชน', example: 'He volunteers in his community.' },
        { word: 'culture', meaning: 'วัฒนธรรม', example: "I'm interested in Japanese culture." },
        { word: 'behavior', meaning: 'พฤติกรรม', example: 'Her behavior surprised everyone.' },
        { word: 'attitude', meaning: 'ทัศนคติ', example: 'He has a positive attitude.' },
        { word: 'solution', meaning: 'ทางแก้ปัญหา', example: 'We need to find a solution.' },
        { word: 'issue', meaning: 'ประเด็นปัญหา', example: 'This is an important issue.' },
        { word: 'average', meaning: 'โดยเฉลี่ย', example: 'The average temperature is 30 degrees.' },
        { word: 'estimate', meaning: 'ประเมิน', example: 'They estimated the cost carefully.' },
        { word: 'reduce', meaning: 'ลด', example: 'We should reduce plastic waste.' },
        { word: 'produce', meaning: 'ผลิต', example: 'The factory produces cars.' },
        { word: 'avoid', meaning: 'หลีกเลี่ยง', example: 'Try to avoid stress.' },
        { word: 'encourage', meaning: 'ให้กำลังใจ / สนับสนุน', example: 'Teachers encourage students to read.' },
        { word: 'participate', meaning: 'เข้าร่วม', example: 'Everyone can participate in the event.' },
        { word: 'volunteer', meaning: 'อาสาสมัคร', example: 'She volunteers at the hospital.' },
        { word: 'deadline', meaning: 'กำหนดส่ง', example: 'We have a tight deadline.' },
        { word: 'schedule', meaning: 'ตารางเวลา', example: 'Check your schedule for tomorrow.' },
      ],
      phrases: [
        { en: 'In my opinion, ...', th: 'ในความเห็นของฉัน...', context: 'แสดงความคิดเห็น' },
        { en: 'I\'d rather stay home.', th: 'ฉันอยากอยู่บ้านมากกว่า', context: 'ความชอบ' },
        { en: 'It\'s worth trying.', th: 'น่าลอง', context: 'ให้กำลังใจ' },
        { en: 'Could you elaborate on that?', th: 'อธิบายเพิ่มเติมได้ไหม', context: 'ขอรายละเอียด' },
      ],
      dialogues: [
        {
          title: 'สัมภาษณ์งาน',
          lines: [
            { speaker: 'HR', en: 'Tell me about your previous experience.', th: 'เล่าประสบการณ์ก่อนหน้านี้หน่อย' },
            { speaker: 'Candidate', en: 'I have worked in marketing for three years.', th: 'ฉันทำงานการตลาดมา 3 ปี' },
            { speaker: 'HR', en: 'Why do you want to join our company?', th: 'ทำไมอยากเข้าร่วมบริษัทเรา' },
            { speaker: 'Candidate', en: 'I believe I can contribute to your team\'s growth.', th: 'ฉันเชื่อว่าช่วยพัฒนาทีมได้' },
          ],
        },
      ],
      sentences: [
        { en: 'I have never tried sushi before.', th: 'ฉันไม่เคยกินซูชิมาก่อน', note: 'Present Perfect' },
        { en: 'If I had more time, I would learn French.', th: 'ถ้ามีเวลามากขึ้น ฉันจะเรียนภาษาฝรั่งเศส', note: 'Second Conditional' },
        { en: 'The report was completed yesterday.', th: 'รายงานเสร็จเมื่อวาน', note: 'Passive' },
      ],
    },

    B2: {
      name: 'Upper Intermediate',
      nameTh: 'กลาง-สูง',
      color: '#8b5cf6',
      description: 'สื่อสารคล่องแคล่ว อธิบายมุมมองที่ซับซ้อน เข้าใจเนื้อหาเชิงนามธรรม',
      canDo: ['โต้แย้งและให้เหตุผลซับซ้อน', 'เขียนเรียงความเชิงวิเคราะห์', 'เข้าใจภาพยนตร์และรายการโทรทัศน์', 'เจรจาธุรกิจ', 'ใช้ภาษาเชิงอ้อม'],
      grammar: [
        { topic: 'Second Conditional', rule: 'If + Past, would + V — สมมติฐานที่ไม่เป็นจริง', examples: ['If I were rich, I would travel the world.', 'If she studied more, she would pass.'] },
        { topic: 'Third Conditional', rule: 'If + Past Perfect, would have + V3 — เสียดายเรื่องในอดีต', examples: ['If I had known, I would have helped.', 'If they had left earlier, they wouldn\'t have missed the train.'] },
        { topic: 'Modal verbs (deduction)', rule: 'must, might, can\'t สำหรับเดา/สรุป', examples: ['She must be at home.', 'It might rain later.', 'He can\'t have finished already.'] },
        { topic: 'Relative clauses', rule: 'who, which, that, whose ขยายคำนาม', examples: ['The man who called is my boss.', 'This is the book that I recommended.'] },
      ],
      vocabulary: [
        { word: 'ambiguous', meaning: 'คลุมเครือ', example: 'His instructions were ambiguous.' },
        { word: 'resilient', meaning: 'ยืดหยุ่น', example: 'She is remarkably resilient under pressure.' },
        { word: 'inevitable', meaning: 'หลีกเลี่ยงไม่ได้', example: 'Change is inevitable in business.' },
        { word: 'comprehensive', meaning: 'ครอบคลุม', example: 'We need a comprehensive solution.' },
        { word: 'procrastinate', meaning: 'ผัดวันประกันพรุ่ง', example: 'Don\'t procrastinate on important tasks.' },
        { word: 'sustainable', meaning: 'ยั่งยืน', example: 'Sustainable development benefits everyone.' },
        { word: 'endeavor', meaning: 'ความพยายาม', example: 'Space exploration is a noble endeavor.' },
        { word: 'perseverance', meaning: 'ความอดทน', example: 'Success requires perseverance and dedication.' },
        { word: 'controversial', meaning: 'เป็นที่ถกเถียง', example: "It's a controversial topic." },
        { word: 'significant', meaning: 'สำคัญมาก', example: 'This is a significant discovery.' },
        { word: 'phenomenon', meaning: 'ปรากฏการณ์', example: 'Climate change is a global phenomenon.' },
        { word: 'contradict', meaning: 'ขัดแย้ง', example: 'His statement contradicts the facts.' },
        { word: 'justify', meaning: 'ให้เหตุผลสนับสนุน', example: 'Can you justify this decision?' },
        { word: 'perspective', meaning: 'มุมมอง', example: 'Try to see it from her perspective.' },
        { word: 'assumption', meaning: 'ข้อสันนิษฐาน', example: "That's a dangerous assumption." },
        { word: 'consequence', meaning: 'ผลที่ตามมา', example: 'Every action has consequences.' },
        { word: 'implement', meaning: 'นำไปปฏิบัติ', example: 'We will implement the new policy.' },
        { word: 'innovative', meaning: 'สร้างสรรค์นวัตกรรม', example: "It's an innovative solution." },
        { word: 'sophisticated', meaning: 'ซับซ้อน / มีระดับ', example: 'The system is very sophisticated.' },
        { word: 'versatile', meaning: 'อเนกประสงค์ / รอบด้าน', example: 'She is a versatile actress.' },
        { word: 'dilemma', meaning: 'สถานการณ์กลืนไม่เข้าคายไม่ออก', example: 'He faced a moral dilemma.' },
        { word: 'skeptical', meaning: 'ขี้สงสัย / ไม่เชื่อง่าย', example: "I'm skeptical about that claim." },
        { word: 'overwhelming', meaning: 'ท่วมท้น', example: 'The support was overwhelming.' },
        { word: 'underlying', meaning: 'ซ่อนอยู่เบื้องหลัง', example: 'We must find the underlying cause.' },
        { word: 'contemporary', meaning: 'ร่วมสมัย', example: 'She studies contemporary art.' },
        { word: 'constitute', meaning: 'ประกอบขึ้นเป็น', example: 'These rules constitute the agreement.' },
        { word: 'facilitate', meaning: 'ทำให้ง่ายขึ้น / เอื้ออำนวย', example: 'Technology facilitates communication.' },
        { word: 'controversy', meaning: 'ข้อโต้แย้ง', example: 'The plan caused a lot of controversy.' },
        { word: 'tackle', meaning: 'จัดการแก้ไข', example: 'We need to tackle this problem.' },
        { word: 'undermine', meaning: 'บ่อนทำลาย', example: 'Doubt can undermine confidence.' },
        { word: 'profound', meaning: 'ลึกซึ้ง', example: 'The book had a profound impact.' },
        { word: 'arguably', meaning: 'อาจกล่าวได้ว่า', example: 'This is arguably the best solution.' },
        { word: 'legitimate', meaning: 'ถูกต้องตามกฎหมาย / สมเหตุสมผล', example: 'She has a legitimate reason.' },
        { word: 'paradox', meaning: 'ความขัดแย้งในตัวเอง', example: "It's a paradox worth exploring." },
        { word: 'viable', meaning: 'เป็นไปได้จริง', example: 'Is this plan financially viable?' },
        { word: 'explicit', meaning: 'ชัดเจน / เปิดเผย', example: 'Give explicit instructions.' },
        { word: 'implicit', meaning: 'โดยนัย', example: 'There was an implicit warning in his tone.' },
        { word: 'mitigate', meaning: 'บรรเทา', example: 'Steps were taken to mitigate the risk.' },
        { word: 'plausible', meaning: 'ฟังดูเป็นไปได้', example: "That's a plausible explanation." },
        { word: 'discrepancy', meaning: 'ความไม่สอดคล้องกัน', example: 'There is a discrepancy in the report.' },
      ],
      phrases: [
        { en: 'From my perspective, ...', th: 'จากมุมมองของฉัน...', context: 'มุมมองส่วนตัว' },
        { en: 'It goes without saying that...', th: 'ไม่ต้องบอกก็รู้ว่า...', context: 'เน้นความชัดเจน' },
        { en: 'I take your point, however...', th: 'เข้าใจที่คุณบอก แต่...', context: 'โต้แย้งสุภาพ' },
        { en: 'To put it bluntly, ...', th: 'พูดตรงๆ ก็คือ...', context: 'พูดตรง' },
      ],
      dialogues: [
        {
          title: 'ประชุมธุรกิจ',
          lines: [
            { speaker: 'Manager', en: 'We need to address the declining sales figures.', th: 'เราต้องแก้ปัญหายอดขายลด' },
            { speaker: 'Analyst', en: 'The data suggests we should target a younger demographic.', th: 'ข้อมูลชี้ว่าควรกลุ่มลูกค้าวัยรุ่น' },
            { speaker: 'Manager', en: 'What would be the estimated cost of that campaign?', th: 'ค่าใช้จ่ายแคมเปญประมาณเท่าไหร่' },
            { speaker: 'Analyst', en: 'I\'d estimate around fifty thousand dollars.', th: 'ประมาณ 50,000 ดอลลาร์' },
          ],
        },
      ],
      sentences: [
        { en: 'Had I known about the meeting, I would have prepared slides.', th: 'ถ้ารู้เรื่องประชุม ฉันจะเตรียมสไลด์', note: 'Third Conditional inverted' },
        { en: 'The project, which took two years, was finally completed.', th: 'โปรเจกต์ที่ใช้เวลา 2 ปี เสร็จสมบูรณ์', note: 'Relative clause' },
        { en: 'She might have forgotten about the appointment.', th: 'เธออาจลืมนัด', note: 'Modal deduction past' },
      ],
    },

    C1: {
      name: 'Advanced',
      nameTh: 'สูง',
      color: '#ec4899',
      description: 'ใช้ภาษาได้ยืดหยุ่์เพื่อวัตถุประสงค์ทางสังคม วิชาการ และมืออาชีพ',
      canDo: ['เขียนรายงานและบทความเชิงวิชาการ', 'เข้าใจนัยและอารมณ์ขัน', 'นำเสนออย่างมีโครงสร้าง', 'ใช้คำศัพท์เฉพาะทาง', 'ปรับระดับภาษาตามบริบท'],
      grammar: [
        { topic: 'Inversion', rule: 'กลับลำดับประธาน-กริยาเพื่อเน้น', examples: ['Never have I seen such beauty.', 'Not only did she win, but she broke the record.'] },
        { topic: 'Cleft sentences', rule: 'เน้นส่วนหนึ่งของประโยค', examples: ['It was John who called.', 'What I need is more time.'] },
        { topic: 'Subjunctive', rule: 'โหมดสมมติในภาษาเป็นทางการ', examples: ['I suggest that he be present.', 'It is essential that she arrive on time.'] },
        { topic: 'Discourse markers', rule: 'เชื่อมความคิดในการเขียน/พูดขั้นสูง', examples: ['Nevertheless, the results were positive.', 'Conversely, the other group declined.'] },
      ],
      vocabulary: [
        { word: 'meticulous', meaning: 'พิถีพิถัน', example: 'She is meticulous about every detail.' },
        { word: 'eloquent', meaning: 'มีวาทศิลป์', example: 'He delivered an eloquent speech.' },
        { word: 'paradigm', meaning: 'แบบแผน', example: 'This represents a paradigm shift.' },
        { word: 'ubiquitous', meaning: 'มีอยู่ทุกที่', example: 'Smartphones are ubiquitous nowadays.' },
        { word: 'pragmatic', meaning: 'ปฏิบัติได้จริง', example: 'We need a pragmatic approach.' },
        { word: 'nuance', meaning: 'ความแตกต่างเล็กน้อย', example: 'There is a subtle nuance in meaning.' },
        { word: 'coherent', meaning: 'สอดคล้องกัน', example: 'Present a coherent argument.' },
        { word: 'scrutinize', meaning: 'ตรวจสอบอย่างละเอียด', example: 'The committee will scrutinize the proposal.' },
        { word: 'exacerbate', meaning: 'ทำให้แย่ลง', example: 'The delay exacerbated the problem.' },
        { word: 'ostensibly', meaning: 'ดูเหมือนว่า (แต่จริงอาจไม่ใช่)', example: 'He left, ostensibly to buy food.' },
        { word: 'corroborate', meaning: 'ยืนยันสนับสนุน', example: 'New evidence corroborates her testimony.' },
        { word: 'dichotomy', meaning: 'ความขัดแย้งสองขั้ว', example: 'There is a dichotomy between theory and practice.' },
        { word: 'tenuous', meaning: 'เปราะบาง / ไม่มั่นคง', example: 'The connection is tenuous at best.' },
        { word: 'cogent', meaning: 'น่าเชื่อถือ / มีเหตุผลหนักแน่น', example: 'She made a cogent argument.' },
        { word: 'proliferate', meaning: 'แพร่กระจายอย่างรวดเร็ว', example: 'Social media platforms have proliferated.' },
        { word: 'inherent', meaning: 'โดยธรรมชาติ / แต่กำเนิด', example: 'There are inherent risks in this plan.' },
        { word: 'deference', meaning: 'ความเคารพยำเกรง', example: 'He spoke with deference to his elders.' },
        { word: 'connotation', meaning: 'ความหมายแฝง', example: 'The word has a negative connotation.' },
        { word: 'discern', meaning: 'แยกแยะ / มองออก', example: 'It is hard to discern the truth.' },
        { word: 'empirical', meaning: 'เชิงประจักษ์', example: 'The study is based on empirical data.' },
        { word: 'conducive', meaning: 'เอื้อต่อการ', example: 'A quiet room is conducive to studying.' },
        { word: 'ambivalent', meaning: 'รู้สึกสองจิตสองใจ', example: 'She felt ambivalent about the offer.' },
        { word: 'anomaly', meaning: 'ความผิดปกติ', example: 'The results showed an unusual anomaly.' },
        { word: 'circumvent', meaning: 'หลีกเลี่ยง (กฎ)', example: 'They tried to circumvent the rules.' },
        { word: 'deleterious', meaning: 'เป็นอันตราย', example: 'Smoking has a deleterious effect on health.' },
        { word: 'epitomize', meaning: 'เป็นตัวอย่างที่ดีที่สุด', example: 'Her work epitomizes creativity.' },
        { word: 'impetus', meaning: 'แรงกระตุ้น', example: 'The award gave her impetus to continue.' },
        { word: 'innate', meaning: 'โดยกำเนิด', example: 'Curiosity is an innate human trait.' },
        { word: 'intrinsic', meaning: 'โดยเนื้อแท้', example: 'Money has no intrinsic value.' },
        { word: 'mundane', meaning: 'ธรรมดาน่าเบื่อ', example: 'He was tired of the mundane routine.' },
        { word: 'plethora', meaning: 'จำนวนมากมาย', example: 'There is a plethora of options.' },
        { word: 'rhetoric', meaning: 'วาทศิลป์ / การใช้คำพูดโน้มน้าว', example: 'Political rhetoric can be misleading.' },
        { word: 'substantiate', meaning: 'ยืนยันด้วยหลักฐาน', example: 'Can you substantiate that claim?' },
        { word: 'tangential', meaning: 'ออกนอกเรื่อง', example: 'His comments were tangential to the topic.' },
        { word: 'vindicate', meaning: 'พิสูจน์ความบริสุทธิ์ / ความถูกต้อง', example: 'The results vindicated her theory.' },
        { word: 'antithesis', meaning: 'สิ่งที่ตรงข้ามอย่างสิ้นเชิง', example: 'His calm was the antithesis of panic.' },
        { word: 'capricious', meaning: 'แปรปรวน / เอาแน่เอานอนไม่ได้', example: 'The weather here is capricious.' },
        { word: 'dogmatic', meaning: 'ยึดติดความเชื่อโดยไม่ฟังเหตุผล', example: 'He is dogmatic about his opinions.' },
        { word: 'impartial', meaning: 'เป็นกลาง / ไม่ลำเอียง', example: 'Judges must remain impartial.' },
        { word: 'malleable', meaning: 'ยืดหยุ่นปรับเปลี่ยนได้', example: 'Young minds are more malleable.' },
      ],
      phrases: [
        { en: 'It is imperative that we act now.', th: 'เราต้องลงมือทันที', context: 'เป็นทางการ' },
        { en: 'The implications are far-reaching.', th: 'ผลกระทบกว้างขวาง', context: 'วิเคราะห์' },
        { en: 'To all intents and purposes, ...', th: 'โดยพื้นฐานแล้ว...', context: 'สรุป' },
        { en: 'Notwithstanding the challenges, ...', th: 'แม้มีอุปสรรค...', context: 'เขียนเชิงวิชาการ' },
      ],
      dialogues: [
        {
          title: 'อภิปรายเชิงวิชาการ',
          lines: [
            { speaker: 'Prof.', en: 'The hypothesis warrants further investigation.', th: 'สมมติฐานนี้ควรศึกษาเพิ่ม' },
            { speaker: 'Student', en: 'Would you say the correlation implies causation?', th: 'ความสัมพันธ์นี้หมายถึงสาเหตุ-ผลไหม' },
            { speaker: 'Prof.', en: 'Not necessarily — we must account for confounding variables.', th: 'ไม่จำเป็น ต้องพิจารณาตัวแปรรบกวน' },
            { speaker: 'Student', en: 'I see. A longitudinal study might yield more conclusive data.', th: 'เข้าใจ การศึกษาระยะยาวน่าจะได้ข้อมูลชัดเจนกว่า' },
          ],
        },
      ],
      sentences: [
        { en: 'Rarely do we encounter such a compelling argument.', th: 'แทบไม่เจอข้อโต้แย้งน่าเชื่อถือเช่นนี้', note: 'Inversion' },
        { en: 'It is the methodology that distinguishes this research.', th: 'วิธีการวิจัยคือสิ่งที่แตกต่าง', note: 'Cleft sentence' },
        { en: 'The findings, albeit preliminary, are encouraging.', th: 'ผลลัพธ์แม้ยังเบื้องต้น ก็น่าสนใจ', note: 'Formal connector' },
      ],
    },

    C2: {
      name: 'Proficiency',
      nameTh: 'เชี่ยวชาญ',
      color: '#ef4444',
      description: 'เข้าใจทุกสิ่งที่ได้ยินและอ่น สรุปข้อมูลจากแหล่งต่างๆ แสดงออกได้อย่างคล่องแคล่ว',
      canDo: ['เข้าใจภาษาพูดเร็วและสำเนียงต่างๆ', 'เขียนบทความวิชาการระดับมหาวิทยาลัย', 'ใช้สำนวนและอุปมาได้ถูกต้อง', 'แปลความนัยเชิงวัฒนธรรม', 'สื่อสารระดับเจ้าของภาษา'],
      grammar: [
        { topic: 'Ellipsis & substitution', rule: 'ละคำที่ซ้ำเพื่อความกระชับและเป็นธรรมชาติ', examples: ['I think so. / I hope not.', 'She works harder than I do.'] },
        { topic: 'Fronting', rule: 'ย้ายส่วนประโยคมาไว้หน้าเพื่อเน้น', examples: ['Especially important is the first chapter.', 'Gone are the days when we waited.'] },
        { topic: 'Mixed conditionals', rule: 'ผสมเวลาระหว่างเงื่อนไข', examples: ['If I had studied medicine, I would be a doctor now.', 'If she were more confident, she would have applied.'] },
        { topic: 'Advanced passive structures', rule: 'รูป passive ที่ซับซ้อน', examples: ['He is believed to have left the country.', 'The issue is being dealt with.'] },
      ],
      vocabulary: [
        { word: 'quintessential', meaning: 'เป็นตัวแทนที่สุด', example: 'She is the quintessential professional.' },
        { word: 'ephemeral', meaning: 'ชั่วคราว', example: 'Fame can be ephemeral.' },
        { word: 'juxtaposition', meaning: 'การวางเคียงกัน', example: 'The juxtaposition of old and new is striking.' },
        { word: 'vicarious', meaning: 'ผ่านประสบการณ์ของผู้อื่น', example: 'She lived vicariously through her travels.' },
        { word: 'idiosyncrasy', meaning: 'ลักษณะเฉพาะตัว', example: 'Everyone has their little idiosyncrasies.' },
        { word: 'perfunctory', meaning: 'ผ่านๆ ไม่ตั้งใจ', example: 'He gave a perfunctory nod.' },
        { word: 'serendipity', meaning: 'โชคดีโดยบังเอิญ', example: 'Finding that book was pure serendipity.' },
        { word: 'unequivocal', meaning: 'ชัดเจนไม่คลุมเครือ', example: 'She gave an unequivocal answer.' },
        { word: 'cacophony', meaning: 'เสียงอึกทึกไม่ประสาน', example: 'The cacophony of the city never stops.' },
        { word: 'equanimity', meaning: 'ความสงบใจ', example: 'She faced the crisis with equanimity.' },
        { word: 'obfuscate', meaning: 'ทำให้สับสน / คลุมเครือ', example: 'The report seemed designed to obfuscate the truth.' },
        { word: 'panacea', meaning: 'ทางออกที่แก้ได้ทุกอย่าง', example: 'There is no panacea for economic problems.' },
        { word: 'sanguine', meaning: 'มองโลกในแง่ดี', example: 'He remained sanguine despite the setbacks.' },
        { word: 'surreptitious', meaning: 'แอบทำอย่างลับๆ', example: 'She made a surreptitious glance at her phone.' },
        { word: 'ineffable', meaning: 'ไม่อาจบรรยายเป็นคำพูดได้', example: 'The beauty of the sunset was ineffable.' },
        { word: 'magnanimous', meaning: 'ใจกว้าง / มีน้ำใจ', example: 'He was magnanimous in victory.' },
        { word: 'obstreperous', meaning: 'ดื้อรั้นอึกทึก', example: 'The obstreperous crowd refused to quiet down.' },
        { word: 'perspicacious', meaning: 'หลักแหลม / มองการณ์ไกล', example: "Her perspicacious analysis impressed everyone." },
        { word: 'recalcitrant', meaning: 'ดื้อดึงไม่ยอมทำตาม', example: 'The recalcitrant employee refused new procedures.' },
        { word: 'sycophant', meaning: 'คนประจบสอพลอ', example: 'He was surrounded by sycophants.' },
        { word: 'taciturn', meaning: 'เงียบขรึม / พูดน้อย', example: 'The taciturn old man rarely spoke.' },
        { word: 'ubiquity', meaning: 'การมีอยู่ทุกหนแห่ง', example: 'The ubiquity of smartphones has changed society.' },
        { word: 'venerable', meaning: 'น่าเคารพนับถือ (จากอายุ/ประสบการณ์)', example: 'The venerable professor has taught for decades.' },
        { word: 'zeitgeist', meaning: 'จิตวิญญาณแห่งยุคสมัย', example: 'The film captured the zeitgeist of the era.' },
        { word: 'abstruse', meaning: 'ยากจะเข้าใจ / ลึกลับซับซ้อน', example: 'The lecture was too abstruse for beginners.' },
        { word: 'acumen', meaning: 'ไหวพริบ / สติปัญญาเฉียบแหลม', example: 'She has great business acumen.' },
        { word: 'cajole', meaning: 'เกลี้ยกล่อม', example: 'He cajoled his sister into helping.' },
        { word: 'deracinate', meaning: 'ถอนรากถอนโคน', example: 'War can deracinate entire communities.' },
        { word: 'equivocate', meaning: 'พูดคลุมเครือหลีกเลี่ยงคำตอบ', example: 'The politician equivocated when asked directly.' },
        { word: 'garrulous', meaning: 'ช่างพูด / พูดมาก', example: 'Her garrulous uncle told endless stories.' },
        { word: 'hegemony', meaning: 'การครอบงำ / อำนาจเหนือ', example: 'The empire maintained hegemony for centuries.' },
        { word: 'iconoclast', meaning: 'ผู้ท้าทายความเชื่อดั้งเดิม', example: 'He was known as an artistic iconoclast.' },
        { word: 'impecunious', meaning: 'ยากจน / ขัดสน', example: 'The impecunious student worked two jobs.' },
        { word: 'inchoate', meaning: 'เพิ่งเริ่มก่อตัว / ยังไม่สมบูรณ์', example: 'The plan was still inchoate.' },
        { word: 'laconic', meaning: 'พูดสั้นกระชับ', example: 'His laconic reply surprised the reporters.' },
        { word: 'mellifluous', meaning: 'ไพเราะนุ่มนวล (เสียง)', example: 'Her mellifluous voice calmed the audience.' },
        { word: 'obviate', meaning: 'ขจัดความจำเป็น', example: 'Early planning can obviate future problems.' },
        { word: 'parsimonious', meaning: 'ตระหนี่ / ประหยัดเกินไป', example: 'He was notoriously parsimonious with money.' },
        { word: 'pernicious', meaning: 'เป็นภัยร้ายแรงอย่างค่อยเป็นค่อยไป', example: 'Prejudice can have a pernicious effect on society.' },
        { word: 'verisimilitude', meaning: 'ความสมจริง', example: 'The afilm was praised for its verisimilitude.' },
      ],
      phrases: [
        { en: 'The crux of the matter is...', th: 'แก่นแท้ของเรื่องคือ...', context: 'สรุปประเด็น' },
        { en: 'By and large, ...', th: 'โดยรวมแล้ว...', context: 'สรุปภาพรวม' },
        { en: 'Be that as it may, ...', th: 'อย่างไรก็ตาม...', context: 'เปลี่ยนประเด็น' },
        { en: 'To the best of my knowledge, ...', th: 'เท่าที่ฉันทราบ...', context: 'ระมัดระวัง' },
      ],
      dialogues: [
        {
          title: 'วิเคราะห์เชิงลึก',
          lines: [
            { speaker: 'A', en: 'The author\'s use of irony underscores the futility of war.', th: 'การใช้อิโรนีของผู้เขียนเน้นความไร้จุดหมายของสงคราม' },
            { speaker: 'B', en: 'Precisely — and the fragmented narrative mirrors societal disintegration.', th: 'ถูกต้อง — การเล่าเรื่องแบบแตกส่วนสะท้อนสังคมที่แตกแยก' },
            { speaker: 'A', en: 'Would you argue the protagonist is an unreliable narrator?', th: 'ตัวเอกเป็น narrator ที่ไม่น่าเชื่อถือไหม' },
            { speaker: 'B', en: 'Undoubtedly. The ambiguity is entirely deliberate.', th: 'แน่นอน ความคลุมเครือเป็นเจตนา' },
          ],
        },
      ],
      sentences: [
        { en: 'So eloquent was her speech that the audience was moved to tears.', th: 'สุนทรพจน์ของเธอโดนใจผู้ฟังจนน้ำตาไหล', note: 'Fronting + inversion' },
        { en: 'The policy, having been thoroughly debated, was finally ratified.', th: 'นโยบายที่ถกเถียงมาอย่างทั่วถึง ได้รับการอนุมัติ', note: 'Perfect participle clause' },
        { en: 'He speaks as if he owned the place.', th: 'เขาพูดเหมือนเป็นเจ้าของที่นี่', note: 'Subjunctive as if' },
      ],
    },
  },

  vocabulary: [
    { word: 'accomplish', meaning: 'ทำสำเร็จ', phonetic: '/əˈkʌmplɪʃ/', example: 'She accomplished her goals.', level: 'B1' },
    { word: 'hello', meaning: 'สวัสดี', phonetic: '/həˈloʊ/', example: 'Hello! Nice to meet you.', level: 'A1' },
    { word: 'travel', meaning: 'เดินทาง', phonetic: '/ˈtrævl/', example: 'I love to travel.', level: 'A2' },
    { word: 'ambiguous', meaning: 'คลุมเครือ', phonetic: '/æmˈbɪɡjuəs/', example: 'His answer was ambiguous.', level: 'B2' },
    { word: 'meticulous', meaning: 'พิถีพิถัน', phonetic: '/məˈtɪkjələs/', example: 'She is meticulous.', level: 'C1' },
    { word: 'serendipity', meaning: 'โชคดีโดยบังเอิญ', phonetic: '/ˌserənˈdɪpəti/', example: 'Pure serendipity.', level: 'C2' },
  ],

  placementTest: {
    title: 'วัดระดับภาษาอังกฤษ',
    description: 'แบบทดสอบ 30 ข้อ เพื่อหาระดับที่เหมาะกับคุณ',
    totalQuestions: 30,
    questions: [
      { q: 'I ___ a student.', options: ['am', 'is', 'are', 'be'], answer: 0 },
      { q: 'She ___ to school every day.', options: ['go', 'goes', 'going', 'went'], answer: 1 },
      { q: 'They ___ watching TV right now.', options: ['is', 'am', 'are', 'be'], answer: 2 },
      { q: 'I ___ to London last year.', options: ['go', 'goes', 'went', 'going'], answer: 2 },
      { q: 'There ___ many books on the shelf.', options: ['is', 'are', 'am', 'be'], answer: 1 },
      { q: 'He ___ speak three languages.', options: ['can', 'cans', 'coulds', 'may'], answer: 0 },
      { q: 'This is ___ apple.', options: ['a', 'an', 'the', '—'], answer: 1 },
      { q: 'I have ___ finished my homework.', options: ['yet', 'already', 'still', 'since'], answer: 1 },
      { q: 'She is ___ than her sister.', options: ['tall', 'taller', 'tallest', 'more tall'], answer: 1 },
      { q: 'If it rains, I ___ stay home.', options: ['will', 'would', 'am', 'was'], answer: 0 },
      { q: 'I have lived here ___ 2019.', options: ['for', 'since', 'from', 'during'], answer: 1 },
      { q: 'The book ___ by millions.', options: ['reads', 'is read', 'was read', 'reading'], answer: 2 },
      { q: 'Could you tell me where ___?', options: ['is the station', 'the station is', 'station is', 'the station'], answer: 1 },
      { q: 'I wish I ___ more time.', options: ['have', 'had', 'has', 'having'], answer: 1 },
      { q: 'By next year, I ___ my degree.', options: ['will complete', 'will have completed', 'completed', 'complete'], answer: 1 },
      { q: 'Neither Tom ___ Jerry was there.', options: ['or', 'nor', 'and', 'but'], answer: 1 },
      { q: 'She suggested ___ early.', options: ['to leave', 'leaving', 'leave', 'left'], answer: 1 },
      { q: 'The meeting has been ___.', options: ['cancel', 'cancelled', 'cancelling', 'cancels'], answer: 1 },
      { q: 'Hardly ___ I arrived when it rained.', options: ['had', 'have', 'has', 'was'], answer: 0 },
      { q: 'Not only did she win, ___ she broke the record.', options: ['and', 'but', 'or', 'so'], answer: 1 },
      { q: 'I\'d rather you ___ smoke here.', options: ['don\'t', 'didn\'t', 'won\'t', 'not'], answer: 1 },
      { q: '___ the weather, we went hiking.', options: ['Although', 'Despite', 'However', 'Because'], answer: 1 },
      { q: 'He denied ___ the money.', options: ['to take', 'taking', 'take', 'taken'], answer: 1 },
      { q: 'It\'s high time we ___ action.', options: ['take', 'took', 'taken', 'taking'], answer: 1 },
      { q: '___ I known, I would have helped.', options: ['Had', 'Have', 'If', 'Would'], answer: 0 },
      { q: 'The phenomenon ___ widely studied.', options: ['has been', 'have been', 'is been', 'was been'], answer: 0 },
      { q: 'She is believed ___ left the country.', options: ['to have', 'having', 'to has', 'have'], answer: 0 },
      { q: 'Rarely ___ such beauty.', options: ['I have seen', 'have I seen', 'I saw', 'did I saw'], answer: 1 },
      { q: 'Be that as it may, ...', options: ['the plan continues', 'the plan continuing', 'the plan continue', 'the plan continued'], answer: 0 },
      { q: 'No sooner ___ the news than shares fell.', options: ['was made', 'had been made', 'made', 'has made'], answer: 1 },
    ],
  },

  progress: {
    weeklyActivity: [
      { day: 'จ', minutes: 35, lessons: 2, vocab: 8 },
      { day: 'อ', minutes: 55, lessons: 3, vocab: 12 },
      { day: 'พ', minutes: 70, lessons: 4, vocab: 15 },
      { day: 'พฤ', minutes: 42, lessons: 2, vocab: 10 },
      { day: 'ศ', minutes: 80, lessons: 5, vocab: 20 },
      { day: 'ส', minutes: 60, lessons: 3, vocab: 14 },
      { day: 'อา', minutes: 52, lessons: 4, vocab: 18, today: true },
    ],
    srsDueLabels: {
      today: 'ครบกำหนดวันนี้', tomorrow: 'พรุ่งนี้', '2days': 'ใน 2 วัน',
      '3days': 'ใน 3 วัน', week: 'ใน 1 สัปดาห์',
    },
    monthlyStats: { totalMinutes: 1240, totalLessons: 48, totalVocab: 312, avgScore: 82, bestStreak: 21 },
  },

  leaderboard: [
    { rank: 1, name: 'สมชาย ใจดี', xp: 4520, avatar: 'ส', tier: 'gold', streak: 45 },
    { rank: 2, name: 'มานี รักเรียน', xp: 4180, avatar: 'ม', tier: 'silver', streak: 38 },
    { rank: 3, name: 'วิชัย เก่งอังกฤษ', xp: 3950, avatar: 'ว', tier: 'bronze', streak: 30 },
    { rank: 8, name: 'สมหญิง วงศ์ดี', xp: 1840, avatar: 'ห', tier: 'you', streak: 14, isYou: true },
  ],

  badges: [
    { icon: '🔥', title: '14 วันติดต่อกัน', earned: true, date: '2026-06-19' },
    { icon: '📚', title: '200 คำศัพท์', earned: true, date: '2026-06-10' },
    { icon: '📖', title: 'อ่านครบทุกระดับ', earned: false, progress: 50 },
  ],

  chatbot: {
    greetings: [
      'สวัสดีค่ะ! เลือกระดับแล้วดูข้อมูลได้เลย หรือถามฉันเรื่องไวยากรณ์และคำศัพท์ได้นะคะ',
    ],
    responses: [
      { keywords: ['a1', 'ระดับ'], reply: 'ระดับ A1 เหมาะกับผู้เริ่มต้น ลองดูส่วน Grammar และ Phrases ของ A1 ก่อนนะคะ' },
      { keywords: ['grammar', 'ไวยากรณ์'], reply: 'เลือกระดับแล้วดูหัวข้อ Grammar พร้อมตัวอย่างประโยคได้เลยค่ะ' },
      { keywords: ['battle', 'ต่อสู้', 'rank'], reply: 'ลอง Word Battle Arena! เรียงคำให้ถูกเพื่อโจมตีศัตรูและเลื่อน Rank นะคะ ⚔️' },
      { keywords: ['hello', 'สวัสดี'], reply: 'Hello! Which level would you like to explore today?' },
    ],
    defaultReplies: [
      'ลองเลือกระดับ A1–C2 ด้านบนเพื่อดูข้อมูลและตัวอย่างนะคะ',
      'เข้า Word Battle เพื่อฝึกเรียงประโยคและแข่ง Rank!',
    ],
  },

  rankTiers: [
    { id: 'bronze', name: 'Bronze', nameTh: 'บรอนซ์', icon: '🥉', color: '#b45309', minRP: 0 },
    { id: 'silver', name: 'Silver', nameTh: 'ซิลเวอร์', icon: '🥈', color: '#94a3b8', minRP: 200 },
    { id: 'gold', name: 'Gold', nameTh: 'โกลด์', icon: '🥇', color: '#f59e0b', minRP: 450 },
    { id: 'platinum', name: 'Platinum', nameTh: 'แพลตินัม', icon: '💎', color: '#22d3ee', minRP: 750 },
    { id: 'diamond', name: 'Diamond', nameTh: 'ไดมอนด์', icon: '👑', color: '#8b5cf6', minRP: 1100 },
    { id: 'master', name: 'Master', nameTh: 'มาสเตอร์', icon: '⚔️', color: '#ef4444', minRP: 1500 },
  ],

  battleOpponents: [
    { id: 'bot-1', name: 'Rookie Bot', avatar: '🤖', rankRP: 50, hp: 80, accuracy: 0.4, damage: 12, level: 'A1' },
    { id: 'bot-2', name: 'Word Slime', avatar: '<img src="assets/word-slime.png" class="avatar-svg" alt="Word Slime" />', avatarType: 'slime', rankRP: 180, hp: 90, accuracy: 0.5, damage: 14, level: 'A1' },
    { id: 'bot-3', name: 'Grammar Goblin', avatar: '👺', rankRP: 320, hp: 100, accuracy: 0.55, damage: 16, level: 'A2' },
    { id: 'bot-4', name: 'Syntax Knight', avatar: '🛡️', rankRP: 500, hp: 110, accuracy: 0.6, damage: 18, level: 'B1' },
    { id: 'bot-5', name: 'Vocab Mage', avatar: '🧙', rankRP: 720, hp: 120, accuracy: 0.65, damage: 20, level: 'B1' },
    { id: 'bot-6', name: 'Phrase Phantom', avatar: '👻', rankRP: 950, hp: 130, accuracy: 0.7, damage: 22, level: 'B2' },
    { id: 'bot-7', name: 'Clause Dragon', avatar: '🐉', rankRP: 1250, hp: 140, accuracy: 0.75, damage: 25, level: 'C1' },
    { id: 'bot-8', name: 'Master Linguist', avatar: '🎓', rankRP: 1600, hp: 150, accuracy: 0.82, damage: 28, level: 'C2' },
  ],

  rankLeaderboard: [
    { name: 'สมชาย ใจดี', avatar: 'ส', rankRP: 1680, wins: 142 },
    { name: 'มานี รักเรียน', avatar: 'ม', rankRP: 1540, wins: 128 },
    { name: 'วิชัย เก่งอังกฤษ', avatar: 'ว', rankRP: 1320, wins: 115 },
    { name: 'นภา สว่างใส', avatar: 'น', rankRP: 1180, wins: 98 },
    { name: 'กิตติ ขยันเรียน', avatar: 'ก', rankRP: 980, wins: 87 },
    { name: 'ปิยะ นักอ่าน', avatar: 'ป', rankRP: 820, wins: 76 },
    { name: 'อรุณ ตะวันทอง', avatar: 'อ', rankRP: 650, wins: 64 },
    { name: 'ธนา พูดเก่ง', avatar: 'ธ', rankRP: 480, wins: 52 },
  ],
};